Repository NguyenThanhLong0/DATN-BEECINEMA, pull requests merged in 2025-02, with the labels that each got.

#14 feat: create food_Management refer:#9
  app/Http/Controllers/Api/FoodController.php
  app/Models/Food.php
  composer.lock
  database/migrations/2025_02_05_145953_create_foods_table.php
  database/seeders/FoodSeeder.php
  routes/api.php
Labels: feature

#16 feat: creat room_Management refer: #5
  app/Http/Controllers/Api/RoomController.php
  app/Models/Branch.php
  app/Models/Cinema.php
  app/Models/Room.php
  app/Models/Seat.php
  app/Models/TypeRoom.php
  app/Models/TypeSeat.php
  database/migrations/2025_02_03_100000_create_type_rooms_table.php
  database/migrations/2025_02_04_112110_create_rooms_table.php
  database/migrations/2025_02_07_100105_create_type_seats_table.php
  database/migrations/2025_02_07_100206_create_seats_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/RoomSeeder.php
  database/seeders/SeatSeeder.php
  database/seeders/TypeRoomSeeder.php
  database/seeders/TypeSeatSeeder.php
  note.md
  routes/api.php
Labels: feature

#19 feat: create typeRoom_Management refer: #17
  app/Http/Controllers/Api/TypeRoomController.php
  note.md
  routes/api.php
Labels: feature

#20 feat: create PostManagement refer: #13
  app/Http/Controllers/Api/PostApiController.php
  app/Models/Post.php
  database/migrations/2025_02_07_075519_creat_posts_table.php
  package-lock.json
  package.json
  resources/views/layouts/app.blade.php
  routes/api.php
  routes/web.php
Labels: feature

#23 feat: create feature typeSeat_Management refer: #22
  app/Http/Controllers/Api/TypeSeatController.php
  note.md
  routes/api.php
Labels: feature

#28 Feature/combo food management refer:#25
  app/Http/Controllers/Api/ComboFoodController.php
  app/Models/Combo.php
  app/Models/ComboFood.php
  app/Models/Food.php
  database/migrations/2025_02_05_100310_create_food_table.php
  database/migrations/2025_02_09_113110_create_combo_food_table.php
  database/seeders/ComboFoodSeeder.php
  database/seeders/DatabaseSeeder.php
  routes/api.php
Labels: feature

#30 Feature/banner management refer:#8
  app/Http/Controllers/Api/BannerController.php
  app/Models/Banner.php
  app/Models/Cinema.php
  composer.lock
  database/migrations/2025_02_04_155000_create_rooms_table.php
  database/migrations/2025_02_12_162739_create_banners_table.php
  routes/api.php
Labels: feature

#31 Feature/movie managerment
  app/Http/Controllers/Api/BranchController.php
  app/Http/Controllers/Api/ComboFoodController.php
  app/Http/Controllers/Api/MovieController.php
  app/Http/Controllers/Api/RoomController.php
  app/Http/Controllers/Api/SeatTemplateController.php
  app/Http/Requests/Api/StoreMovieRequest.php
  app/Http/Requests/Api/UpdateMovieRequest.php
  app/Models/Movie.php
  app/Models/MovieVersion.php
  database/migrations/2025_02_10_052316_create_movies_table.php
  database/migrations/2025_02_10_073511_create_movie_versions_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/MovieVersionSeeder.php
  database/seeders/MoviesSeeder.php
  routes/api.php
Labels: feature

#35 Feature/banner management refer:#8
  database/seeders/BannerSeeder.php
  database/seeders/DatabaseSeeder.php
Labels: Update

#36 Hot fix/fix combo refer:#34
  app/Http/Controllers/Api/ComboController.php
  app/Http/Controllers/Api/ComboFoodController.php
  app/Models/Combo.php
  app/Models/Food.php
  database/migrations/2025_02_09_113110_create_combo_food_table.php
  database/seeders/ComboSeeder.php
  database/seeders/FoodSeeder.php
Labels: bug

#41 #39 update user migrate
  database/migrations/2014_10_12_000000_create_users_table.php
Labels: feature

#45 feat: update food refer:#9
  app/Http/Controllers/Api/FoodController.php
  composer.lock
Labels: Update

#46 Feature/ranks management refer:#44
  app/Http/Controllers/Api/RankController.php
  app/Models/Rank.php
  database/migrations/2025_02_17_135217_create_ranks_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/RankSeeder.php
  routes/api.php
Labels: feature

#51 Feature/showtime management
  app/Http/Controllers/Api/AuthController.php
  app/Http/Controllers/Api/ShowtimeController.php
  app/Http/Requests/Api/StoreShowtimeRequest.php
  app/Http/Requests/Api/UpdateShowtimeRequest.php
  app/Models/Cinema.php
  app/Models/Movie.php
  app/Models/MovieVersion.php
  app/Models/Post.php
  app/Models/Room.php
  app/Models/Seat.php
  app/Models/SeatShowtime.php
  app/Models/Showtime.php
  app/Models/User.php
  app/Models/Voucher.php
  composer.lock
  database/migrations/2025_02_15_160130_create_showtimes_table.php
  database/migrations/2025_02_17_000000_create_users_table.php
  database/migrations/2025_02_17_075519_create_posts_table.php
  database/migrations/2025_02_17_083340_create_seat_showtimes_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/SeatSeeder.php
  database/seeders/SeatShowtimeSeeder.php
  database/seeders/ShowtimeSeeder.php
  note.md
  package-lock.json
  routes/api.php
Labels: feature

#55 feature ticket#15
  app/Http/Controllers/Api/CinemaController.php
  app/Http/Controllers/Api/TicketController.php
  app/Models/ComboFood.php
  app/Models/Movie_Version.php
  app/Models/Showtime.php
  app/Models/Ticket.php
  database/migrations/2025_02_13_134504_create_movie_table.php
  database/migrations/2025_02_13_140048_create_movie_version_table.php
  database/migrations/2025_02_13_140105_create_showtime_table.php
  database/migrations/2025_02_13_140254_create_movie__ticket_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/MovieSeeder.php
  database/seeders/ShowtimeSeeder.php
  database/seeders/TicketSeeder.php
  routes/api.php
Labels: feature

#56 feat: create moviesClientHome refer:#49
  app/Http/Controllers/Api/MovieController.php
  database/seeders/MoviesSeeder.php
  routes/api.php
Labels: feature

#58 Feature/movies client home refer:#49
  app/Http/Controllers/Api/MovieClientHomeController.php
  app/Http/Controllers/Api/MovieController.php
  routes/api.php
Labels: feature

#59 Feature/movie review refer:#52
  app/Http/Controllers/Api/CinemaController.php
  app/Http/Controllers/Api/MovieController.php
  app/Http/Controllers/Api/MovieReviewController.php
  app/Models/Movie.php
  app/Models/MovieReview.php
  database/factories/MovieReviewFactory.php
  database/migrations/2025_02_19_085635_create_movie_reviews_table.php
  database/seeders/MovieReviewSeeder.php
  routes/api.php
Labels: feature

#60 feat: update ComboController refer:#34
  app/Http/Controllers/Api/ComboController.php
  database/migrations/2025_02_05_100310_create_food_table.php
  database/migrations/2025_02_08_100210_create_combos_table.php
  routes/api.php
Labels: feature

#62 feat: update MoviesClientHome refer:#49
  app/Http/Controllers/Api/ComboController.php
  app/Http/Controllers/Api/MovieClientHomeController.php
Labels: Update

#65 Client develop
  app/Http/Controllers/Api/AuthController.php
  app/Http/Controllers/Api/BranchController.php
  app/Http/Controllers/Api/CinemaController.php
  app/Http/Controllers/Api/ShowtimeController.php
  app/Http/Requests/Api/StoreShowtimeRequest.php
  routes/api.php
Labels: bug

#67 Feature/page showtime refer: #61
  app/Http/Controllers/Api/ShowtimeController.php
  routes/api.php
  routes/web.php
Labels: Update

#70 feat: add showtimeMovie refer: #69
  app/Http/Controllers/Api/ShowtimeController.php
Labels: add

#71 Client develop
  app/Http/Controllers/Api/MovieClientHomeController.php
  app/Http/Controllers/Api/MovieController.php
  app/Http/Controllers/Api/ShowtimeController.php
  app/Http/Controllers/Api/VoucherApiController.php
  routes/api.php
Labels: bug

#78 Client develop
  app/Events/SeatStatusChange.php
  app/Http/Controllers/Api/ChooseSeatController.php
  app/Http/Controllers/Api/ShowtimeController.php
  app/Jobs/BroadcastSeatStatusChange.php
Labels: bug

#79 fix realtime and api
  app/Events/ChangeSeat.php
  app/Events/SeatStatusChange.php
  app/Http/Controllers/Api/ChooseSeatController.php
  app/Http/Controllers/Api/ShowtimeController.php
  composer.json
  composer.lock
  config/broadcasting.php
Labels: Hot fix
