Repository NguyenThanhLong0/DATN-BEECINEMA, pull requests merged in 2025-03, with the labels that each got.

#88 Feature/hot fixshowtime
  app/Http/Controllers/Api/ChooseSeatController.php
  app/Http/Controllers/Api/ShowtimeController.php
  app/Http/Controllers/Api/UserController.php
  composer.lock
  note.md
  routes/api.php
Labels: Hot fix

#89 updateSeatHoldTime new
  app/Http/Controllers/Api/ShowtimeController.php
Labels: Hot fix

#93 feature/gg_login #92
  app/Http/Controllers/Api/AuthController.php
  composer.json
  composer.lock
  config/app.php
  config/services.php
  routes/api.php
Labels: feature

#101 fix api payment
  app/Http/Controllers/Api/PaymentController.php
Labels: bug

#109 feat: creat sendMailTickit refer:#108
  app/Http/Controllers/Api/PaymentController.php
  app/Jobs/SendTicketEmail.php
  app/Mail/TicketBookedMail.php
  app/Models/Seat.php
  app/Models/Ticket.php
  app/Models/Ticket_Seat.php
  resources/views/emails/ticket_booked.blade.php
Labels: feature

#115 feat: update Momo refer:#106
  app/Http/Controllers/Api/PaymentController.php
Labels: Update

#122 feat: update MOMO refer:#106
  app/Http/Controllers/Api/PaymentController.php
Labels: Update

#127 Feature/fix combo price payment
  app/Http/Controllers/Api/PaymentController.php
Labels: Hot fix

#131 feat:update paymentIpn refer:#106
  app/Http/Controllers/Api/PaymentController.php
Labels: Update

#133 feat: update momo refer:#106
  app/Http/Controllers/Api/PaymentController.php
Labels: Update

#134 feat: update Statistics refer:#129
  app/Http/Controllers/Api/ReportController.php
Labels: Update

#146 Feature/showtime multiday
  app/Http/Controllers/Api/ShowtimeController.php
  app/Http/Requests/Api/StoreShowtimeRequest.php
  app/Models/Branch.php
  routes/api.php
Labels: Hot fix
